AskMePortal/Controllers/AddUsersController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using AskMePortal.Data;
using AskMePortal.Models.Account;
using AskMePortal.Helpers;
using System;

namespace AskMePortal.Controllers
{
    [Authorize(Roles = "SuperAdmin")]
    public class AddUsersController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;

        public AddUsersController(UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
        }

        [HttpGet]
        public IActionResult AddUsers()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddUsers(AddUsersVM model)
        {
            if (!(model.UserType == ApplicationUserRoles.AppUser.ToString() || model.UserType == ApplicationUserRoles.Admin.ToString()))
            {
                ModelState.AddModelError(string.Empty, "User type is invalid!");
                return View(model);
            }
            if (ModelState.IsValid)
            {
                var user = model.MapToApplicationUser();
                user.CreatedDate = DateTime.Now;
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    await _userManager.AddToRoleAsync(user, model.UserType);
                    ModelState.Clear();
                    ViewBag.Message = "Hurray user created!";
                    return View();
                }

                AddErrors(result);
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }
        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
        }

    }
}

AskMePortal/Controllers/NewSurveyController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using AskMePortal.Data;
using AskMePortal.Models.NewSurvey;
using AskMePortal.Services;

namespace AskMePortal.Controllers
{
    [Authorize(Roles = "Admin,SuperAdmin")]
    public class NewSurveyController : Controller
    {
        private readonly SurveyService _surveyService;
        private readonly UserManager<ApplicationUser> _userManager;

        public NewSurveyController(SurveyService surveyService, UserManager<ApplicationUser> userManager)
        {
            _surveyService = surveyService;
            _userManager = userManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(NewSurveyVM newSurveyVM)
        {
            var userId = _userManager.GetUserId(User);
            bool result = _surveyService.CreateSurvey(newSurveyVM, userId);
            ViewBag.Message = result ? "New Survey was created !" : "Something went wrong...";
            return View("Index");
        }
    }
}

AskMePortal/Controllers/ResultsController.cs
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using AskMePortal.Models.Results;
using AskMePortal.Services;

namespace AskMePortal.Controllers
{
    [Authorize(Roles = "Admin,SuperAdmin")]
    public class ResultsController : Controller
    {
        private readonly SurveyService _surveyService;

        public ResultsController(SurveyService surveyService)
        {
            _surveyService = surveyService;
        }

        [HttpGet]
        public IActionResult Index(int? surveyId)
        {
            var resultVM = new ResultsVM()
            {
                AllSurveys = _surveyService.GetAllSurveys().Select(a =>
                                         new SelectListItem
                                         {
                                             Value = a.Id.ToString(),
                                             Text = a.Name
                                         }).ToList()
            };

            if (surveyId == null)
            {
                return View(resultVM);
            }

            resultVM.ResultsQuestions = _surveyService.GetResultsBySurveyId(surveyId.Value).ToList();

            if (!resultVM.ResultsQuestions.Any())
            {
                ViewBag.Message = "There are no results for chosen survey yet...";
            }

            return View(resultVM);
        }
    }
}

AskMePortal/Controllers/SurveysListController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using AskMePortal.Services;
using System.Collections.Generic;
using AskMePortal.Models.SurveysList;

namespace AskMePortal.Controllers
{
    [Authorize(Roles = "Admin,SuperAdmin")]
    public class SurveysListController : Controller
    {
        private readonly SurveyService _surveyService;

        public SurveysListController(SurveyService surveyService)
        {
            _surveyService = surveyService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var surveys = OrderSurveys(_surveyService.GetAllSurveys()).ToList();
            return View(surveys);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CloseSurvey(int surveyId)
        {
            bool result = _surveyService.CloseSurvey(surveyId);
            ViewBag.Message = result ? "Survey was closed successfully" : "Closing survey has failed";
            var surveys = OrderSurveys(_surveyService.GetAllSurveys()).ToList();
            return View("Index", surveys);
        }

        public IEnumerable<SurveysListVM> OrderSurveys(IEnumerable<SurveysListVM> surveys)
        {
            var orderedSurveys = surveys.OrderByDescending(x => x.CreatedDate).ThenByDescending(x => x.IsActive);
            return orderedSurveys;
        }
    }
}

AskMePortal/Views/Shared/NotFound.cshtml
@{
    ViewData["Title"] = "Not Found";
    Layout = "_EmptyLayout";
}

<link href="~/css/errorCodePages.css" rel="stylesheet" />
<div class="message">
    <h1>404</h1>
    <h2>Oops!</h2>
    <h3>Page not found...</h3>
</div>

AskMePortal/Views/Shared/_EmptyLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>AskMEPortal</title>
    <environment include="Development">
        <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
        <link href="~/css/login.css" rel="stylesheet" />
        <link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link href="~/css/emptyLayout.min.css" rel="stylesheet" />
    </environment>

</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/emptyLayout.min.js" asp-append-version="true"></script>
    </environment>
</body>
</html>

AskMePortal/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using AskMePortal.Data
@using AskMePortal.Helpers

@inject UserManager<ApplicationUser> _userManager

@{
    var userId = _userManager.GetUserId(User);
    var currentUser = await _userManager.FindByIdAsync(userId);
    var themeSkin = "skin-blue";
}

<!DOCTYPE html>
<html>
<head>
    <base href='@Url.AbsoluteContent("~/")'>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <environment include="Development">
        <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
        <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
        <link href="~/css/sourceSansPro.css" rel="stylesheet" />
        <link href="~/lib/admin-lte/css/AdminLTE.min.css" rel="stylesheet" />
        <link href="~/css/site.css" rel="stylesheet" />
        <link href="~/lib/jqueryui/jquery-ui.min.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link href="~/css/askmeportal.min.css" rel="stylesheet" />
    </environment>
    @{
        if (User.IsInRole("Admin"))
        {
            themeSkin = "skin-green";
            <link href="~/lib/admin-lte/css/skins/skin-green.min.css" rel="stylesheet" />
        }
        else if (User.IsInRole("SuperAdmin"))
        {
            themeSkin = "skin-purple";
            <link href="~/lib/admin-lte/css/skins/skin-purple.min.css" rel="stylesheet" />
        }
        else
        {
            <link href="~/lib/admin-lte/css/skins/skin-blue.min.css" rel="stylesheet" />
        }
    }
</head>

<body class="hold-transition @themeSkin sidebar-mini ">
    <div class="wrapper">
        <header class="main-header">
            <a asp-controller="Home" asp-action="Index" class="logo">
                <span class="logo-mini"><img src="~/img/logo200x200.png" width="40" height="40" /></span>
                <span class="logo-lg">
                    AskMePortal
                    <img src="~/img/logo200x200.png" width="40" height="40" class="mb-4" />
                </span>
            </a>
            <nav class="navbar" role="navigation">
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src='@currentUser.AvatarUrl' class="user-image rounded-circle" alt="User Image" />
                                <span>@currentUser.FirstName @currentUser.LastName</span>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="user-header">
                                    <img src='@currentUser.AvatarUrl' class="rounded-circle" alt="User Image" />
                                    <p>
                                        @currentUser.FirstName @currentUser.LastName - @currentUser.JobTitle
                                        <small>Member since 2019</small>
                                    </p>
                                </li>
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="@currentUser.ProfileUrl" target="_blank" class="btn btn-default btn-flat">Profile</a>
                                    </div>
                                    <div class="pull-right">
                                        <form asp-controller="Account" asp-action="LogOff" method="post" id="logoutForm">
                                            <button type="submit" class="btn btn-default btn-flat">Sign out</button>
                                        </form>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <aside class="main-sidebar">
            <section class="sidebar">
                <div class="user-panel">
                    <div class="pull-left image">
                        <img src='@currentUser.AvatarUrl' class="rounded-circle" alt="User Image" />
                    </div>
                    <div class="pull-left info">
                        <p>@currentUser.FirstName</p>
                        <div><i class="fa fa-circle text-success"></i> online</div>
                    </div>
                </div>
                <ul class="sidebar-menu">
                    @{
                        if (User.IsInRole("Admin") || User.IsInRole("SuperAdmin"))
                        {
                            <li>
                                <a asp-controller="NewSurvey" asp-action="Index" class="sidebar-toggle" role="button">
                                    <i class="fa fa-plus-square"></i>
                                    <span>New Survey</span>
                                </a>
                            </li>
                            <li>
                                <a asp-controller="SurveysList" asp-action="Index" class="sidebar-toggle" role="button">
                                    <i class="fa fa-list-ul"></i>
                                    <span>Surveys List</span>
                                </a>
                            </li>
                            <li>
                                <a asp-controller="AssignToUsers" asp-action="Index" class="sidebar-toggle" role="button">
                                    <i class="fa fa-vcard-o"></i>
                                    <span>Assign to users</span>
                                </a>
                            </li>
                            <li>
                                <a asp-controller="Results" asp-action="Index" class="sidebar-toggle" role="button">
                                    <i class="fa fa-line-chart"></i>
                                    <span>Results</span>
                                </a>
                            </li>
                            <li>
                                <a asp-controller="UsersProfiles" asp-action="Index" class="sidebar-toggle" role="button">
                                    <i class="fa fa-users"></i>
                                    <span>Users</span>
                                </a>
                            </li>
                        }
                        if (User.IsInRole("AppUser"))
                        {
                            <li>
                                <a asp-controller="ActiveSurveys" asp-action="Index" class="sidebar-toggle" role="button">
                                    <i class="fa fa-bar-chart"></i> <span>Active surveys</span>
                                </a>
                            </li>
                        }
                        if (User.IsInRole("SuperAdmin"))
                        {
                            <li>
                                <a asp-controller="AddUsers" asp-action="AddUsers" class="sidebar-toggle" role="button">
                                    <i class="fa fa-user-plus"></i> <span>Add Users</span>
                                </a>
                            </li>
                        }
                    }

                </ul>
            </section>
        </aside>
        <div class="content-wrapper">
            <section class="content">
                @RenderBody()
            </section>
        </div>
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                Made by: <strong>me!</strong>
            </div>
            <strong>Copyright &copy; 2020 <a href="#">AskMEPortal</a>.</strong> All rights reserved.
        </footer>
    </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/popper.js/umd/popper.min.js"></script>
        <script src="~/lib/jqueryui/jquery-ui.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
        <script src="~/lib/admin-lte/js/app.min.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <script src="~/js/lteLayout.js"></script>
        <script src="~/js/infoDialog.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/askmeportal.min.js" asp-append-version="true"></script>
    </environment>

    @if (ViewBag.Message != null)
    {
        <div id="dialog-confirm" title="Info">
            <p>@ViewBag.Message</p>
        </div>
        <script>
            ShowInfoDialog();
        </script>
    }
    @RenderSection("Scripts", required: false)
</body>
</html>