AskMePortal/Models/ActiveSurveys/ActiveSurveysVM.cs
using System;

namespace AskMePortal.Models.ActiveSurveys
{
    public class ActiveSurveysVM
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime Created { get; set; }
        public bool IsCompleted { get; set; }
    }
}

AskMePortal/Controllers/ActiveSurveysController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using AskMePortal.Data;
using AskMePortal.Models;
using AskMePortal.Services;

namespace AskMePortal.Controllers
{
    [Authorize(Roles = "AppUser")]
    public class ActiveSurveysController : Controller
    {
        private readonly SurveyService _surveyService;
        private readonly UserManager<ApplicationUser> _userManager;

        public ActiveSurveysController(SurveyService surveyService, UserManager<ApplicationUser> userManager)
        {
            _surveyService = surveyService;
            _userManager = userManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var userId = _userManager.GetUserId(User);
            var activeSurveys = _surveyService.GetFillableSurveysById(userId).ToList();
            return View(activeSurveys);
        }

        [HttpGet]
        public IActionResult GetSurvey(int surveyId)
        {
            var userId = _userManager.GetUserId(User);
            var activeSurvey = _surveyService.GetActiveSurveyById(surveyId, userId);
            return View("Survey", activeSurvey);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SubmitSurvey(SurveyVM surveyVM)
        {
            var userId = _userManager.GetUserId(User);
            bool result = _surveyService.SaveAnswers(surveyVM, userId);
            var fillableSurveys = _surveyService.GetFillableSurveysById(userId).ToList();
            ViewBag.Message = result ? "Answers were saved successfully!" : "Something went wrong when saving answers...";
            return View("Index", fillableSurveys);
        }
    }
}

AskMePortal/Views/ActiveSurveys/Index.cshtml
@model List<AskMePortal.Models.ActiveSurveys.ActiveSurveysVM>

@{
    ViewData["Title"] = "Active Surveys";
}

<div class="page-wrapper-title">
   All active surveys
    <hr />
</div>
<div class="page-card-wrapper">
    @{

        if (Model?.Count > 0)
        {
            foreach (var survey in Model)
            {
                <h3>@survey.Name</h3> <text>Created: @survey.Created.ToString("f")</text>
                if (!survey.IsCompleted)
                {
                    <a asp-controller="ActiveSurveys" asp-action="GetSurvey" asp-route-surveyId="@survey.Id" class="btn btn-info">Start</a>
                }
            }
        }
        else
        {
            <p>No active surveys!</p>
        }
    }
</div>

AskMePortal/Views/ActiveSurveys/Survey.cshtml
@using AskMePortal.Helpers;
@model AskMePortal.Models.SurveyVM

@{
    ViewData["Title"] = "Active Surveys";
}
<div class="page-wrapper-title">
    You can fill in your survey here
    <hr />
</div>

<div class="page-card-wrapper">
    <form asp-action="SubmitSurvey" id="submitSurvey">
        <div class="time-info">Created: @Model.Created.ToString("f")</div>
        <div class="survey-title-box mb-5">
            @Model.Name
        </div>
        @{
            for (int i = 0; i < Model.Questions.Count(); i++)
            {
                var questionNo = i + 1;
                var questionType = Model.Questions[i].QuestionInputType;
                <div class="form-group">
                    <label>@questionNo. @Model.Questions[i].Value</label>

                    @if (questionType == QuestionType.checkbox)
                    {
                        <div class="checkbox-wrapper">
                            <input name="surveyVM.Questions[@i].QuestionAnswer" value="true"
                                   type="@questionType.ToString()" />
                        </div>
                        <input type="hidden" value="false" name="surveyVM.Questions[@i].QuestionAnswer" />

                    }
                    else
                    {
                        <input name="surveyVM.Questions[@i].QuestionAnswer" value="@Model.Questions[i].QuestionAnswer"
                               type="@questionType.ToString()" required class="form-control" />
                    }

                    <input type="hidden" name="surveyVM.Questions[@i].QuestionId" value="@Model.Questions[i].QuestionId" />
                    <input type="hidden" name="surveyVM.Questions[@i].QuestionInputType" value="@questionType" />
                </div>
            }
        }

        <input type="hidden" name="surveyVM.SurveyId" value="@Model.SurveyId" />
        <div class="form-group text-right">
            <button class="btn btn-primary waves-effect">
                Send <i class="fa fa-paper-plane ml-1"></i>
            </button>
        </div>
    </form>
</div>
@section Scripts{
    <script>
        $("#submitSurvey").validate();
    </script>
}